---
version: '3.8'
services:
  postgres:
    build:
      context: ./postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=mlflow,airflow,titanic
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-store:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  mlflow:
    restart: always
    depends_on:
      - postgres
    build:
      context: ./mlflow
    container_name: mlflow_server
    expose:
        - "5000"
    ports:
        - "5000:5000"
    command: mlflow server --backend-store-uri postgresql://mlflow:mlflow@postgres:5432/mlflow --default-artifact-root /mlflow --host 0.0.0.0
